name: Cowsay-ASCII
on:
    push

jobs:
    First_Job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay
              run: sudo apt install cowsay -y

            - name: Adding Cowsay dragon version
              run: cowsay -f dragon "Run for cover, ROAR." >> dragon.txt

            - name: Display the content
              run: cat dragon.txt

            - name: List the file in the repo
              run: ls -ltrh
         