name: first_workflow
on: push

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Step_1
        uses: actions/checkout@v4
      - name: Step_2
        run: ls
      - name: Step_3
        run: cat README.md
